### ISSUE TITLE
Installation fails for Visual Studio 2012 Update 5

### ISSUE THREAD

**Issue by crapp** [CoatiSoftware/vs-sourcetrail#2]
I Just tried to install this extension for Visual Studio 2012 Update 5. I wasn't able to find it in the marketplace (why??) so I downloaded the file and executed it. The installation process stops with an error and see lots of log messages. See the attached file. 

[VSIXInstaller_26509f7e-8990-4204-b33b-59f2eb6ede50.log.txt](https://github.com/CoatiSoftware/vs-sourcetrail/files/1159422/VSIXInstaller_26509f7e-8990-4204-b33b-59f2eb6ede50.log.txt)

Seems like it doesn't like the Visual Studio Build Tools 2017 but why didn't it install the extension for vs2012?

**Comment by mlangkabel** [comment]
@crapp; thanks for reporting this issue! I've investigated a little and it seems that there is an install target missing in the `extension.vsixmanifest` file. The file specifies the target `Microsoft.VisualStudio.Community` for VS2012 to VS2017 where VS Community actually means VS Community and above. 

But there hasn't been a VS Community version for VS 2012 or VS 2013 so I guess that's why Visual Studio thinks that your VS2015 install is not supported.

I just uploaded a new release to the marketplace (called 1.0.1) to validate this theory.

**Comment by crapp** [comment]
Hi, thanks for your quick reply. Indeed I am now able to Install the extension from the market place for VS2012. But after restarting visual studio I see another error message stating it could not load `SourcetrailExtensionPackage`

I suppose this is the relevant part from `C:\Users\myuser\AppData\Roaming\MicrosoftVisualStudio\11.0\ActivityLog.xml`

```
  <entry>
    <record>42</record>
    <time>2017/07/20 06:37:57.315</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [SourcetrailExtensionPackage]</description>
    <guid>{ACF15780-03B5-440E-A41E-DB79B7043FC2}</guid>
  </entry>
  <entry>
    <record>43</record>
    <time>2017/07/20 06:37:57.358</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [SourcetrailExtensionPackage]</description>
    <guid>{ACF15780-03B5-440E-A41E-DB79B7043FC2}</guid>
    <hr>80070002</hr>
    <errorinfo>Die Datei oder Assembly "Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.</errorinfo>
  </entry>
  <entry>
    <record>44</record>
    <time>2017/07/20 06:37:57.358</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [SourcetrailExtensionPackage]</description>
    <guid>{ACF15780-03B5-440E-A41E-DB79B7043FC2}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Die Datei oder Assembly "Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.</errorinfo>
  </entry>
```
This is party in german. Essentially the log messages says File, assembly `Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` or a dependency could not be found. 

This Version **14.0.0.0** looks a bit suspicious.

**Comment by mlangkabel** [comment]
Thank you for testing the new release so quickly. I checked the project file used to build the extension and it states that is uses Version 11 of the Shell assembly. However when opening the project in Visual Studio it somehow loads version 14 of the assembly. 

I will try to fix that by specifying the exact dll to use  instead of trusting Visual Studio with that.

**Comment by mlangkabel** [comment]
@crapp: I think I solved the issue, but to be sure, can you please test this build of the extension?

Download: [vs-sourcetrail-1-0-2.zip](https://github.com/CoatiSoftware/vs-sourcetrail/files/1161862/vs-sourcetrail-1-0-2.zip)

**Comment by crapp** [comment]
I still can't install from a vsix file. The Installer thinks VS2017 BuildTool is a normal VS installation and throws an exception because a File is not found. You should not try to install the extension for build tools only installations (There exists VS2015 Buildtools and VS2017 Buildtools)  See the attached logfile. 

[VSIXInstaller_3c5480f1-4165-4397-a5df-e0f504618c59.log.txt](https://github.com/CoatiSoftware/vs-sourcetrail/files/1162075/VSIXInstaller_3c5480f1-4165-4397-a5df-e0f504618c59.log.txt)

Thats why I used the title 

> Installation fails with Visual Studio 2017 Build Tools installed

**Comment by mlangkabel** [comment]
So actually we are having two separate issues here:
* the extension is not installable for VS2012
* the installer somehow runs into issues when trying to locate Visual Studio-Buildtools 2017

The first issue should be fixed but we need to circumvent the second one in order to validate this. I think it's time to upload another version to the VS Marketplace so we can test this. Please try to update the extension from inside Visual Studio to version 1.0.2

**Comment by crapp** [comment]
I can now intsall the extension from the marketplace and don't see any error messages when visual studio ist started. The SOURCETRAIL menu is visible and I can use it. So one problem solved. Thanks for your efforts!

**Comment by mlangkabel** [comment]
Awesome! Glad I could help. And thanks for your testing. 

I found this [this issue](https://developercommunity.visualstudio.com/content/problem/32018/vsixinstallerexe-cant-install-extensions-when-visu.html) on the Microsoft Developer Community regarding the Visual Studio-Buildtools 2017 related error. Unfortunately it's a Visual Studio issue we cannot do anything about. 

However this may only happen when installing from the downloaded vsix file. Installing from within Visual Studio should work regardless.
